language: node_js
node_js:
- '12'
notifications:
  email:
    on_success: never
    on_failure: always
script: yarn build
deploy:
  provider: npm
  edge: true
  email: npm@jupiterone.io
  api_key:
    secure: VKRVUOOS4HoUJftg/hbRmwZblOXG1Pw6aZ/vbm1HrWPX/met548h0dHPvCDosQrRzm8ad1E8O8IOeo8Rq8KbIJ4sqwQJGCMC+Wvm/9psAhdt2hBYJ6F3O4/RftWWsOukUEwdzL5phxwfO0dHytQe0Bk01o5T0Wd7AqFxNNLEl1BKGxygzDjYSPwlgx0XllRitBFaQQF4crJLre3HSxyYW3fYKZrruMJmDBML6/y8CnjEvViJ+zdSn1EtvldNeUaXatwak6M1AXbkmzlmj9gQglvHDa+lN3TMs39bj1T7tRkY3bgdUpzCS1+LQzCT3O5RCQ7jIJgUqxK30vWhAc468pFzA15PGZ1OYDhvLGWQmaFihA/ZqrUAQgQCPeo23HVtbcu2RrgzIEI+2WGINb9HmlLyOvuB6Nsjs057j95blOvG4k7gOgCuNzFLcF0sKgjis1nRNAwp2v957IZYoAigOqA1YJ/WcEeV1kBQZhoDVkBKll+6LO71zDTObis7dXt6OJo0jTDBm4Lz8uxA2l5soC5TxtxaSNeiI4i/1iemVGJD2N5x/HkyCcoQvDhBcGhEM66QHmxNyyb3UPnSssDjCUkGJllMaVG0X8jJmuuqLc4rmBxD0J+MAyHSvO4hbbGl+d6ltwLJ4ocFW8aBHu2tU5CFjX5kQIO1n2dKZMWjq0k=
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: JupiterOne/graph-crowdstrike
    node: '12'
